package com.ayantsoft.interview.hibernate.pojo;
// Generated 6 Dec, 2016 12:26:16 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Doument generated by hbm2java
 */
@Entity
@Table(name = "doument", catalog = "interview_tracker")
public class Doument implements java.io.Serializable {

	private Integer id;
	private String filePath;
	private Date createdDate;
	private String fileName;
	
	private Set<Candidate> candidates = new HashSet<Candidate>(0);

	public Doument() {
	}

	public Doument(String filePath, Date createdDate, String fileName, Set<Candidate> candidates) {
		this.filePath = filePath;
		this.createdDate = createdDate;
		this.candidates = candidates;
		this.fileName = fileName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "file_path", length = 100)
	public String getFilePath() {
		return this.filePath;
	}
	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doument")
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}
	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

	@Column(name = "file_name", length = 100)
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
}