package com.ayantsoft.interview.hibernate.pojo;
// Generated 6 Dec, 2016 12:26:16 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ContactAdddress generated by hbm2java
 */
@Entity
@Table(name = "contact_adddress", catalog = "interview_tracker", uniqueConstraints = @UniqueConstraint(columnNames = "work_mobile"))
public class ContactAdddress implements java.io.Serializable {

	private Integer id;
	private String address1;
	private String address2;
	private String addressType;
	private String alternateEmail;
	private String city;
	private String country;
	private String email;
	private String homeMobile;
	private String homePhone;
	private String currentLocation;
	private String prefferedLocation;
	private String landMark;
	private String postalCode;
	private String state;
	private String workMobile;
	private Set<Candidate> candidates = new HashSet<Candidate>(0);
	private Set<JobConsultancy> jobConsultancies = new HashSet<JobConsultancy>(0);

	public ContactAdddress() {
	}

	public ContactAdddress(String address1, String address2, String addressType, String alternateEmail, String city,
			String country, String email, String homeMobile, String homePhone, String currentLocation,
			String prefferedLocation, String landMark, String postalCode, String state, String workMobile,
			Set<Candidate> candidates, Set<JobConsultancy> jobConsultancies) {
		this.address1 = address1;
		this.address2 = address2;
		this.addressType = addressType;
		this.alternateEmail = alternateEmail;
		this.city = city;
		this.country = country;
		this.email = email;
		this.homeMobile = homeMobile;
		this.homePhone = homePhone;
		this.currentLocation = currentLocation;
		this.prefferedLocation = prefferedLocation;
		this.landMark = landMark;
		this.postalCode = postalCode;
		this.state = state;
		this.workMobile = workMobile;
		this.candidates = candidates;
		this.jobConsultancies = jobConsultancies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "address1", length = 145)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 145)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "address_type", length = 45)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "alternate_email", length = 50)
	public String getAlternateEmail() {
		return this.alternateEmail;
	}

	public void setAlternateEmail(String alternateEmail) {
		this.alternateEmail = alternateEmail;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "home_mobile", length = 50)
	public String getHomeMobile() {
		return this.homeMobile;
	}

	public void setHomeMobile(String homeMobile) {
		this.homeMobile = homeMobile;
	}

	@Column(name = "home_phone", length = 50)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "current_location", length = 45)
	public String getCurrentLocation() {
		return this.currentLocation;
	}

	public void setCurrentLocation(String currentLocation) {
		this.currentLocation = currentLocation;
	}

	@Column(name = "preffered_location", length = 45)
	public String getPrefferedLocation() {
		return this.prefferedLocation;
	}

	public void setPrefferedLocation(String prefferedLocation) {
		this.prefferedLocation = prefferedLocation;
	}

	@Column(name = "land_mark", length = 145)
	public String getLandMark() {
		return this.landMark;
	}

	public void setLandMark(String landMark) {
		this.landMark = landMark;
	}

	@Column(name = "postal_code", length = 45)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "state", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "work_mobile", unique = true, length = 45)
	public String getWorkMobile() {
		return this.workMobile;
	}

	public void setWorkMobile(String workMobile) {
		this.workMobile = workMobile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactAdddress")
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactAdddress")
	public Set<JobConsultancy> getJobConsultancies() {
		return this.jobConsultancies;
	}

	public void setJobConsultancies(Set<JobConsultancy> jobConsultancies) {
		this.jobConsultancies = jobConsultancies;
	}

}
