package com.ayantsoft.interview.hibernate.pojo;
// Generated 6 Dec, 2016 12:26:16 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobConsultancy generated by hbm2java
 */
@Entity
@Table(name = "job_consultancy", catalog = "interview_tracker")
public class JobConsultancy implements java.io.Serializable {

	private Integer id;
	private ContactAdddress contactAdddress;
	private String consultancyName;
	private String contactPerson;
	private String isActive;
	private int candidateId;
	private Set<Candidate> candidates = new HashSet<Candidate>(0);

	public JobConsultancy() {
	}

	public JobConsultancy(ContactAdddress contactAdddress, int candidateId) {
		this.contactAdddress = contactAdddress;
		this.candidateId = candidateId;
	}

	public JobConsultancy(ContactAdddress contactAdddress, String consultancyName, String contactPerson,
			String isActive, int candidateId, Set<Candidate> candidates) {
		this.contactAdddress = contactAdddress;
		this.consultancyName = consultancyName;
		this.contactPerson = contactPerson;
		this.isActive = isActive;
		this.candidateId = candidateId;
		this.candidates = candidates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_address_id", nullable = false)
	public ContactAdddress getContactAdddress() {
		return this.contactAdddress;
	}

	public void setContactAdddress(ContactAdddress contactAdddress) {
		this.contactAdddress = contactAdddress;
	}

	@Column(name = "consultancy_name", length = 145)
	public String getConsultancyName() {
		return this.consultancyName;
	}

	public void setConsultancyName(String consultancyName) {
		this.consultancyName = consultancyName;
	}

	@Column(name = "contact_person", length = 45)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "is_active", length = 45)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "candidate_id", nullable = false)
	public int getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(int candidateId) {
		this.candidateId = candidateId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobConsultancy")
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

}
